# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bbbea4c9495d5ac2755b843dd3af218eff81e55295c39b74b4e7ed97acd79cb415d094435b2603b37176ad0079d2ae5374741d38bbb4b4f134247b086ff6d365

test:
  secret_key_base: c7f80d4f86a020c8551f0c1a7f10fb3a6db4043f0400e5d6e65eac6f9ada7728e2f68fb474a8f7d684b0da94f0c9fa8ac8cc8ae518542e5e071b7ec44081365e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
